let lastDiagnostic = null;
const POPUP_SETTINGS_KEY = "m365ce_extension_popup_settings_v1";
function isoTimestampForFilename(date = new Date()) { return date.toISOString().replace("T", "_").replace(/:/g, "-"); }
function sanitizeFilenamePart(value) { const raw = String(value || "m365-copilot-extension-output"); const safe = raw.replace(new RegExp("[\\x00-\\x1F<>:\"/\\\\|?*]+", "g"), " ").replace(/\s+/g, " ").trim(); return (safe || "m365-copilot-extension-output").slice(0, 160).replace(/[ .]+$/g, "") || "m365-copilot-extension-output"; }
function longestFenceRun(text, marker) { const matches = String(text || "").match(new RegExp(`${marker}{3,}`, "g")) || []; return matches.reduce((max, item) => Math.max(max, item.length), 0); }
function renderFencedBlock(text, language = "") { const body = String(text ?? ""); const backtickLength = Math.max(3, longestFenceRun(body, "`") + 1); const fence = "`".repeat(backtickLength); return `${fence}${language}\n${body}\n${fence}`; }
function extensionVersion() { return chrome.runtime.getManifest()?.version || "1.0.28"; }
function diagnosticJsonMarkdown(diagnostic, exportedAt = new Date().toISOString()) { return [`## M365 Copilot Chat Conversation Exporter diagnostic`, `- Exported: ${exportedAt}`, `- ExporterVersion: ${extensionVersion()}`, `- ExporterRuntime: browser-extension`, "", renderFencedBlock(JSON.stringify(diagnostic, null, 2), "json"), ""].join("\n"); }
function setText(id, value) { const element = document.getElementById(id); if (element) { element.textContent = value; } }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>"']/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[ch])); }
function showVersion() { setText("extension-version", `v${extensionVersion()}`); }
function loadPopupSettings() { try { return { includeUnclassifiedRecords: true, ...(JSON.parse(localStorage.getItem(POPUP_SETTINGS_KEY) || "{}") || {}) }; } catch { return { includeUnclassifiedRecords: true }; } }
function savePopupSettings(settings) { try { localStorage.setItem(POPUP_SETTINGS_KEY, JSON.stringify(settings)); } catch { /* ignore */ } }
function exportOptionsFromUi() { const checkbox = document.getElementById("include-unclassified-records"); return { includeUnclassifiedRecords: checkbox ? checkbox.checked : true }; }
function hydrateOptionsUi() { const settings = loadPopupSettings(); const checkbox = document.getElementById("include-unclassified-records"); if (!checkbox) { return; } checkbox.checked = settings.includeUnclassifiedRecords !== false; checkbox.addEventListener("change", () => savePopupSettings(exportOptionsFromUi())); }
function appendPopupLine(parent, text, className = "") { const line = document.createElement("div"); if (className) { line.className = className; } line.textContent = text; parent.appendChild(line); return line; }
function renderPageInfo(info) { const panel = document.getElementById("page-info"); if (!panel) { return; } panel.textContent = ""; if (!info?.ok) { appendPopupLine(panel, `Not available: ${info?.error || "unknown error"}`, "bad"); return; } const state = info.active ? "Ready" : "Open an M365 Copilot chat conversation"; const stateLine = appendPopupLine(panel, state, info.active ? "ok" : "bad"); const strong = document.createElement("strong"); strong.className = stateLine.className; strong.textContent = state; stateLine.textContent = ""; stateLine.appendChild(strong); const title = info.chatName || info.title || "not detected"; appendPopupLine(panel, `Conversation: ${title}`, "muted"); appendPopupLine(panel, `ConversationId: ${info.conversationId || "not detected"}`, "muted"); }
async function activeTab() { const tabs = await chrome.tabs.query({ active: true, currentWindow: true }); return tabs[0]; }
async function sendToActiveTab(message) { const tab = await activeTab(); if (!tab?.id) { return { ok: false, error: "No active tab" }; } try { return await chrome.tabs.sendMessage(tab.id, message); } catch (error) { return { ok: false, error: error?.message || String(error) }; } }
function downloadTextFromPopup(filename, text, mimeType = "text/markdown;charset=utf-8") { const safeFilename = sanitizeFilenamePart(filename); const blob = new Blob([text], { type: mimeType }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = safeFilename; document.body.appendChild(anchor); anchor.click(); anchor.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); return { ok: true, filename: safeFilename }; }
function downloadMultipleTextFromPopup(files) { const results = []; for (const file of files || []) { results.push(downloadTextFromPopup(file.filename, file.text, file.mimeType || "text/markdown;charset=utf-8")); } return results; }
function showDiagnostic(payload) { lastDiagnostic = { capturedAt: new Date().toISOString(), result: payload }; setText("result", JSON.stringify(payload, null, 2)); }
async function refreshPageInfo(render = true) { const info = await sendToActiveTab({ type: "M365CE_GET_PAGE_INFO" }); if (info?.ok && info.active) { const summary = await sendToActiveTab({ type: "M365CE_TEST_SUBSTRATE" }); if (summary?.ok) { info.chatName = summary.chatName || summary.title || info.chatName; } } if (render) { renderPageInfo(info); } return info; }
async function exportCurrentConversation() { const button = document.getElementById("export-current"); const oldText = button.textContent; button.disabled = true; button.textContent = "Exporting…"; setText("result", "Exporting readable Markdown and raw JSON Markdown…"); try { const result = await sendToActiveTab({ type: "M365CE_GET_EXPORT_FILES", options: exportOptionsFromUi() }); if (!result?.ok) { showDiagnostic(result); return; } const downloads = downloadMultipleTextFromPopup(result.files || []); setText("result", JSON.stringify({ ok: true, exportedAt: result.exportedAt, downloads, summary: result.summary, rendererVersion: result.rendererVersion, options: exportOptionsFromUi() }, null, 2)); } finally { button.disabled = false; button.textContent = oldText; } }
async function downloadDiagnosticBundle() { const exportedAt = new Date().toISOString(); const timestamp = isoTimestampForFilename(new Date(exportedAt)); const bundle = { ok: true, exportedAt, extensionVersion: extensionVersion(), exporterRuntime: "browser-extension", popupOptions: exportOptionsFromUi() }; setText("result", "Preparing diagnostic bundle…"); bundle.pageInfo = await refreshPageInfo(true); bundle.substrateTest = await sendToActiveTab({ type: "M365CE_TEST_SUBSTRATE" }); bundle.observedCapture = await sendToActiveTab({ type: "M365CE_GET_LAST_CAPTURED" }); lastDiagnostic = { capturedAt: exportedAt, result: bundle }; const baseName = sanitizeFilenamePart(bundle.substrateTest?.chatName || bundle.substrateTest?.conversationId || bundle.pageInfo?.conversationId || "m365-copilot-extension-diagnostic"); const filename = `${baseName}_${timestamp}.diagnostic.json.md`; const download = downloadTextFromPopup(filename, diagnosticJsonMarkdown(lastDiagnostic, exportedAt), "text/markdown;charset=utf-8"); setText("result", JSON.stringify({ ok: true, download, bundle }, null, 2)); }
document.getElementById("refresh-page").addEventListener("click", () => refreshPageInfo(true));
document.getElementById("export-current").addEventListener("click", exportCurrentConversation);
document.getElementById("download-diagnostic-bundle").addEventListener("click", downloadDiagnosticBundle);
showVersion();
hydrateOptionsUi();
refreshPageInfo();
